### ISSUE TITLE
真操蛋

### ISSUE THREAD

**Issue by kabuqinuoyuekayueqinuo** [shadowings-zy/TrainTicketsSystem#4]
瞎几把改尼玛呢 看不出来 数据库有人开发了吗  mmp  表结构都tm改 日了狗了

**Comment by shadowings-zy** [comment]
这位朋友，本项目搭建在我自己的云数据库上，作任何修改都是我自己的自由，如果你想要使用本项目，请自行购买服务器并搭建数据库。
